### ISSUE TITLE
Ruby version requirements not clear

### ISSUE THREAD

**Issue by webmatze** [FidMe/active_mappers#9]
It looks like ActiveMappers needs at least a ruby version >= 2.5.0, but I am not sure.

I would like to use it with ruby versions below 2.5.0 but the use of ruby features like `do ... rescue ... end` prevents that.

**Comment by Michaelvilleneuve** [comment]
Hi, indeed we have not been focused on our ruby version since we force ourselves to keep up with the  latest stable version. 
However I do not see any issues in refactoring active_mappers code to allow older ruby version to work, it would actually be a matter of a few lines of code. 
I'll see if I can work on that soon, in the meantime do not hesitate to open up a pr since it should not be a pain to fix

**Comment by Michaelvilleneuve** [comment]
Could you try changing this : 
```ruby
def self.acts_as_polymorph
      each do |resource|
        mapper = KeyTransformer.resource_to_mapper(resource, self)
        mapper.with(resource, rootless: true)
      rescue NameError
        raise NotImplementedError, 'No mapper found for this type of resource'
      end
    end
```

to this : 
```ruby
def self.acts_as_polymorph
      each do |resource|
        begin
          mapper = KeyTransformer.resource_to_mapper(resource, self)
          mapper.with(resource, rootless: true)
        rescue NameError
          raise NotImplementedError, 'No mapper found for this type of resource'
        end

      end
    end
```

and see if that fixes your issue ? If it does I'll fix in the next release
